_version: "1.0.0"
NuwaTS:
  # https://github.com/Chengyui/NuwaTS
  # https://arxiv.org/pdf/2405.15317
  check_dataloader: False
  TORCH:
    DATASET:
      dataset_type: 'numpy' # or 'class' # custom Class or vanilla dataset from the numpy arrays
      trim_to_size: 96 # null # 512 for MomentFM
      pad_ts: True # will add nans to the end -> multiple of trim_to_size, e.g. 1981 -> 2048
      downsample_factor: null # if trim_to_size is 512 and downsample_factor is 4, original trim size is 3x512=2048
      resample_method: 'linear'
      split_subjects_to_windows: True # Make 4 subsubjects from the original subject
      fill_na: 'median'
    DATALOADER:
      num_workers: 0
      batch_size: 16
      shuffle: False # hard to reshape back to original length if you set this to True
      pin_memory: True
  MODEL:
    detection_type: 'fine-tune' # 'zero-shot'#  #
    train_on: 'pupil_gt' # or 'pupil_raw_imputed'1
    # https://github.com/thuml/Time-Series-Library/blob/main/scripts/anomaly_detection/PSM/TimesNet.sh
    # 'forecasting task, options:[M, S, MS]; M:multivariate predict multivariate,
    #                    S:univariate predict univariate, MS:multivariate predict univariate')
    features: S
    lr: 0.0001
    lradj: 'type1'
    no_epochs: 10
  HYPERPARAMS:
    method: 'GRID'
  SEARCH_SPACE:
    GRID:
      detection_type: ['fine-tune']
