# https://medium.com/@attud_bidirt/automatic-tuning-of-hyper-parameters-of-a-xgboost-classifier-c5588bceda4
TabPFN:
  HYPERPARAMS:
    method: 'GRID'
    metric_val: 'auc'
  SEARCH_SPACE:
    GRID:
     param1: [1, 2, 3]