UniTS:
  check_dataloader: False
  MODEL:
    # Same logic as for MOMENT
    # Use fine-tune if you plan to train something, and zero-shot if you plan to just run an inference
    # (independent of whether you are actually per se finetuning, or training from scratch)
    detection_type: 'fine-tune' # 'zero-shot' -> affects data selection in "dataset_data_array_selector()"
    train_on: 'pupil_gt' # or 'pupil_raw_imputed' -> which col name from the DuckDB dataframe gets picked
  TORCH:
    DATASET:
      dataset_type: 'numpy'
      trim_to_size: 500 # make comparable to Moment size
      pad_ts: True # will add nans to the end -> multiple of trim_to_size, e.g. 1981 -> 2048
      downsample_factor: null # if trim_to_size is 512 and downsample_factor is 4, original trim size is 3x512=2048
      resample_method: 'linear'
      split_subjects_to_windows: True # Make 4 subsubjects from the original subject
      fill_na: 'median'
    DATALOADER:
      num_workers: 0
      batch_size: 16
      shuffle: False # harder to reshape back to original length if you set this to True
      pin_memory: True
  PARAMS:
    # https://github.com/mims-harvard/UniTS/blob/main/scripts/few_shot_anomaly_detection/UniTS_finetune_few_shot_anomaly_detection.sh
    fix_seed: 2021
    ddp: False
    is_training: 1
    subsample_pct: 0.05
    model_id: finetune_few_shot_anomaly_detection_pct05
    pretrained_weight: units_x32_pretrain_checkpoint.pth
    model: UniTS
    prompt_num: 10
    patch_len: 16
    stride: 16
    e_layers: 3
    d_model: 32
    des: 'Exp'
    itr: 1
    lradj: finetune_anl
    learning_rate: 5e-4
    weight_decay: 1e-3
    train_epochs: 10
    batch_size: 32
    acc_it: 32
    dropout: 0
    debug: online
    project_name: anomaly_detection
    clip_grad: 100
    # Data-specific params
    # https://github.com/mims-harvard/UniTS/blob/main/data_provider/anomaly_detection.yaml
    # See TimesNet config which uses similar params
  task_data_config_list:
    task_name: anomaly_detection
    dataset_name: SERI_PLR_GLAUCOMA
    dataset: SERI_PLR_GLAUCOMA
    data: SERI_PLR_GLAUCOMA
    root_path: null
    seq_len: 96
    label_len: 0
    pred_len: 0
    features: S
    embed: timeF
    # Number of features, as we have univariate time series, these are 1?
    enc_in: 1
    dec_in: 1
    c_out: 1